apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ws4wSEhFKzxkFFQRo5K/7+y6uQsmCIgiFS4GpqTk0BGHIbU=,iv:IrqBcezIdrWAxIdI9m783bz8OmBah7JosvbWe7QsqS4=,tag:QXTIlEn0QW5E/TJNe0agew==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:B1/beSEvOKq9P6LVpcZ0dVGfdRJU+FN+q2xzty1xp6MMfZr0ww==,iv:GK350bYOVsOwIQfzVFIWAgwSe/Q1QusnxJ/kME5/Iwc=,tag:iJJFAC0l17l+jDh1RTp6IQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RVaQwOnP3GlDiNDaFG0=,iv:mO2p6ERlXJPKfyyFpSPx7SoRKePSW0YwhGjLJrlmnJc=,tag:CLLjVnt3wXJ9GdghhqG2og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbGJNNi9acjc5ZW05Qy9G
            bWYzS1VqRmU4YmhJR2hXaTdBcmwyM0ZPbDJnCkN6OXJ4RFFFL0tSdW8wemV5UGRy
            WVQ0TEFydllRay9hODhlbzVqZGpOb2cKLS0tIHNsRE42aTNjZ1c0YkZ4MEJJWnRV
            WHNVTDRiVzRBZW85UHk0MDlpRnhDaFUKX/v4XawetkhsPN4gv4rJOlGmd/FcT4bk
            W10+lt61Qc6+tGdmC6xRbTqh6dISIy1k9+9+LSv2tR8KBVTQ/PoM9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T09:19:21Z"
    mac: ENC[AES256_GCM,data:U8rANALzjV2BnneON9pU753Hq2isXcyuUasnlySHMsaD9XTrh53ITWn2lYWmV12r9xIhx1BPVZem/r2ViiFG/0/gaEZoUKRhImmhv4XjSjQgCRH1qv3T9I4dr1jmOXbd6P4C1w1CjHbc2+hpeSZfuZrpR3WpjV3k0tYL2P79+Io=,iv:UFnrc76M/CTRrRtoDCrIYDcxGx5WdlbIn86W/pYHQr0=,tag:ru/6zJc6CMX3TG7Ad9TmZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
