---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
      - name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: nfs
        parameters:
          detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 10.69.4.20
          port: 80
          apiKey: "${TRUENAS_API_KEY}"
          allowInsecure: true
        zfs:
          datasetParentName: nasty/Kubernetes/NFS/v
          detachedSnapshotsDatasetParentName: nasty/Kubernetes/NFS/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.69.4.20
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
