apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: downloads
stringData:
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:s0RD1MWA6TFHAv84tad2,iv:GfUxNF/agW+TcUUVhAqQ6Q2xwqUQiLOPlgGnhnm8W5c=,tag:jqps1vp/eDkrGy+QtMs8zw==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:t7IaTbk=,iv:uEQF3ifS27pNeystMSbiThKaWDFcEkvzFZfwYBDq7DI=,tag:CZSW/Rtj6bZZyUNrfh7NKQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:L72DcxYEJUAi3Mubo2/ra6tdjzXRMxA7ab6OjDcuM7C82Y0lXQ4qwkYCAnw=,iv:yiyOwtPLhrdobkW+hx/N1rHzY+6L9q81q2DPdiv9tww=,tag:qSmZ3Rkej6JLiFQ9b+Rmng==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:lj+SU6fFuK3VhFbGvlSGrBRXc8vD5h37SOnGKnwqz8ceB1hIceP6DLyAxzI=,iv:UxUthnOifdDpstSdFfer6ngG98T8ph0+NOlMjovTUi4=,tag:yfqmmHmsNOyPSKh/s7UmVg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:qYgOTwaGuEeUs7pXdTgR,iv:qx1M0rfsofjzemVbSEIp8OtOQaDdUPQx5OdZxTs+ZPI=,tag:rgSGgbpy1NesDWy4Qx5PAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ1U2M3IrcXJrWGlRYXJs
            N0hVQUFjZTFPckoyTWZob1JaaVZ2OUp1RlJVCkF0SHVZWFpYZVZRbld1ZzlJWHZT
            N0VRMnFtUVpvSjZvTm9VUTBIQ1AxTWsKLS0tIGtuMnMzTTFDV2Q5RU1xdXUwWEoy
            SDlEdnYySUlLQ0Uva0I0V2RKMm1LVUEKZxHs6wMaYtkeqVF+qc/n8yB/Aw7jsAKP
            P6ki+SngJTBgCQcJGvo0WiPLq2NnJQD+SttKD1yJP8gFAaM7/Oeeng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-20T07:05:58Z"
    mac: ENC[AES256_GCM,data:0FaCA1Q1Cx9zIiuZGTRlTHMGSTjByAOph4FRFvhKm2z0l6+lgH9movycTW5qWM7H5Wy7UzIsCjI+NRK+Arxikt62/059PCee/y2v81rj8wbeC+S0PVP/LFqPhqlmoRZFI9dr11CRlrqiDXfKmy5+uLWznHov3tWuk0YJS6qEgyY=,iv:/Z4XVucKlGdybzq7BPNw/cSoTpLuueZCfqWYgMXTRpg=,tag:fo4K6tAsiruoLsa29735nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
