---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations:
    "goldilocks.fairwinds.com/enabled": "true"
    k8tz.io/strategy: "hostPath"
