kind: ENC[AES256_GCM,data:Gd9BIeeN,iv:tdM329/+GFi0ub8AAi9bu2HqpEnFpZaU5QJMAWL9pWI=,tag:zIBnFjgdvru9tDULExPmjg==,type:str]
ansible_user: ENC[AES256_GCM,data:4oInVg66,iv:Uelxl/sbHdJ2T0vjk5q5nfiLDIDROzsvo8+sr0ZoCEU=,tag:RAZRKi8xdoYAud6rgZfCFg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zVyU+el/IS0cChqocqrNnYfHd+AXGbGwzT/JjSHv93DSw+tXDDePwIA=,iv:J5fqwgHMlGaXpdOhH3FOJd4cUTNWrIdr2rj5AnOBIWE=,tag:t7yXCvZiWvrEIeKNtUbOtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY2ZCTlI3VURCRTA1cXlh
            NWYwWWpHZWlqOHQzL0ZLQUViOEtYcDM2andRCmJuT0ZiSGJPS2ptVGp5aEdkMloy
            UVpzRVZjUEl0NmJyVXowVXN4THNYencKLS0tIGFHUXRHWi84SWRHWjJHRW5lbXNG
            Q1NWUTZxTGNiUUdld3hpOHRoY1RKS3MKsdHdfuZgfz06cuTKGjlJ/nckcTSemtZ/
            R/KH9eKc9gZMrfdg9eA5zK/q8pzW+kxzbMroGb5coPsMUb2uMVufUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T09:22:49Z"
    mac: ENC[AES256_GCM,data:Ob/gXomEdhDjVaiKqbj2G9m0yTdFQWOS4AMVSD5ZekWh02cc2W95yMmUNDBh+MqX0BixOBink7lyl1HvHOqGvstvBNMEQ8E0wMNK7Ws/K2e1RxW/1HIxXpEUOvnevvfQa5IdR1/O5xuTaY9ssLqtY0u/4/+VjuvURZrNdQXRlz8=,iv:pnbZj/GcG0OTbG8zu8AsK66aI5qxvXBGS25jFDP5qb8=,tag:tgeoZa5Ur/24ZHsljaJnVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
