kind: ENC[AES256_GCM,data:KTKfpCQF,iv:v2uSxvi9d5JUw0ttRgT2SaDI0LkWy+4p6Y/6KI7y+wk=,tag:8YTO9/NBNKsQtWVzkivvyA==,type:str]
ansible_user: ENC[AES256_GCM,data:up0ImdXn,iv:7W9cF51AJ+nsYEpKAheejbgziDevpcJP9CxKp2gtv0U=,tag:OiEtxywZFxR9zNwVBNQdyw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:eU6vX2/TaA9VeJqFQ8Ml0O8dkYE=,iv:hks56Rw9lpEc9vy17pvGXfyx54x9qJSHGSBKem3I+Uc=,tag:tsc5Hvg6ijfEyXz2VMcMmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSTd4TmExTWJaaCtLWnZP
            WitrZTRBWkQyUEhLVDhwWStyRVVZMS82bUIwCjZBenBpYzBhbVphTEdmV1p6d0dj
            MnR6RHFrNmZkVFkxM3N0Y01BRmFFSHcKLS0tIFIzdXQ3VTIzL0NxM1FleFRpZHVP
            NkFrNWVwMWxjYnMrRzViTkZrVVkwa3cKN9zA/LwJ13WtXvPNRge0CN3IzP6MLpP7
            b4umJ+oTOv/MzGxYuNBemSxPBZ44DwS/DRtT7ys46j57o9LyOPtHyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T10:54:07Z"
    mac: ENC[AES256_GCM,data:MxzyxWFO44OkvoOaRh6CcBEtW+I988Qp6fvvW1exmvvNqvmM1zCM0bSq9dVuR9HAnLSfbMcpbt52aoZTlRfw/japf7KHmw22oGen96RkCXyF6pd2D1T2mdcmUTKmsx5+Rg8ZYhem4IzEpm0U5O+KemAmoStz01mYbXcVbyuNGS0=,iv:cSD4oQK7TiyugWPiX43camQ35Zk5qcVRq1HJIFhwrBA=,tag:oeK1CzVgL5OJvp4qrTzU/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
