kind: ENC[AES256_GCM,data:JvlpajUX,iv:cKIBl/YUvjWmxFjSE/yC1B9PFGXcPhuiCNO9AKLBVeE=,tag:F+6uUjdbTnMzNV58siNqmw==,type:str]
ansible_user: ENC[AES256_GCM,data:hd3cR1dj,iv:sNr2S4tfJkJP/jlP7XT09SZ1z3f1mhWTfHRBc6+owjg=,tag:NQRtYVtgD1TRyOIRhQz1uw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9Lyai3I9EeYhused3Y/sgiqqKT0=,iv:j48rT5BBIXXu3ffrAkjI/+Zj92hWxlMN+DxtRJSuLRY=,tag:2vZwz4lAWUZcyBnin2YtIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRllNeDZUL2R6VkxHUkNP
            bTAwdWwzeGhqbjY1U0R2M1ZLbnBtU2hoTEV3CmNmelFhWHFIZm9yL292UVlnRE16
            aFB0bUQ4cU80STE4TXZLd0JvditEY0kKLS0tIDhpdmJUTGY5Z2EzUE9DZGFUR0pR
            NzYrbEdWOGdGVGJnaXVQbTJleWlvZDAK+5dvcNAp4DpCDCgJaoiDZtgannNvicq4
            JNj7zbxIboo9RYuwhn1d6wBDOvq08ZvNtW9z/3X/TisCKtaaKv9XYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T10:54:07Z"
    mac: ENC[AES256_GCM,data:gKMJM8TrXPTvfkzNZ8alEH0vH1qJ5Yqp7iMpz72Tovk2jXC6bosafhjrPvFObaHT6BAVaY16/IwRIwpBT/dN/nIMUgImEzVh87G1l8zNH2xsosjitJhwlvoXcxkuNgfMre8Bjzsupxa6OhqOHIej/ptnoFWCimW2/koxs+SomtQ=,iv:jpNgKSmKsIzsQV4gsLf2tC2L2BxWExsA15/oB5tBdLE=,tag:Lt0Tlt4mhRf4br3f1Vq1wQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
