kind: ENC[AES256_GCM,data:QsDyCgxd,iv:aYO6uwB1W8jRyjUV2YnIz0nePaOqQbBm31zWL7jBxgY=,tag:EhOIX86B+lYOl/4JlzDz1g==,type:str]
ansible_user: ENC[AES256_GCM,data:GuxajWCq,iv:YUd8Uq0kH+R1Rvps2uI72hdDiEQ9XyNe/oEhmV79c6M=,tag:E2MbH5zVl9+0MZ7l6SiZJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5mtguUgTfCqiiV6xhezUMSArGj8=,iv:Ak8XBgj669ERXFbJye9veiFLbjavrTBvOqKZ7QtxI3Q=,tag:QyVH5XQ4aAnQ0NfgW5bLEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdjlMR0dlcG1iQXI1MXlL
            TVNNZzVLZ3Byd0VaNE5xanlqWTZHUjNRQ1ZFCmxxUC9LUTZ5Yy9yc2xwYlVmZXlV
            dGRkc3Y3RDJDZDJyQ0hLUmNQT0gzb1UKLS0tIHJzTkk1OEFncXJRVmNsOFgvV3cw
            RTRzcWtFQmVoNDN2UjA0M3NQLzRmZW8Kr9ZWRQ8WCC0Ix0f6dnSjOrQLTqBeztui
            fkOxlYKJAe/p6PBBXO4NChvuazjWkhzqosC6mPWsyB5YnJH+qIDemg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T21:47:38Z"
    mac: ENC[AES256_GCM,data:KxfdK2WxvG4emAX2PhtFHK1L/XKMy4+EwT0cZo/avTK6iCFoj4XgXMSE+iaYqMozFxFry2ykMhKhZO/47UG5GUn/A8E17Bh00+dKki+vF3VEPPgLylLo3qaH2JlaQkGp1+ypWZ5qAPaAhA3RshjznqrqyUO9Q+XCiLsa2UjIrEI=,iv:DNLBuLnxEVMPBr3GJpTmTu+N1ZLM7pqSHZ2pfhGYO1o=,tag:D/GQjuz/93LIWPZNRyBrNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
