kind: ENC[AES256_GCM,data:y2Vigi9M,iv:K45Gb9AthakPf/7plQ7W6Gr/gK9X+B1r8tYYhvhunos=,tag:nESl5AjABoVtN1PNSTwekg==,type:str]
ansible_user: ENC[AES256_GCM,data:wjlnATBc,iv:IgAqWPmuy/VbFOb7ozlIMuQSu4gp0aB2YXfSK2av/uw=,tag:0YmYcgV6W15yq6ltcdZOIg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CV2WV3vBjP8EHDdh8k1/KO8qcO0=,iv:SBL5UCm9qwsp+rkbG1SGBaobTOZz35ziwIvsBj0FJbE=,tag:ufLJxQ+g4uI0uBwDmcHbOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TSsxY0RLMEl4bGNHNzBE
            N1dhVmJiUW1uN2hpcUU5ZHZYcDNSc3l3ZHhzCitMMFJGVlhMdmVjOVo0R05acmFW
            UlYzZ3dnUm5mTzRKQzFJMnE1ZlVNalkKLS0tIDZ1RWZlZHdXNlliSlM3R1NKWXpF
            bmFzeFZETDdHWjRaaEliNklnQWkzRGMKlYFrlTydziUcfOrZ6yMyOwDmKhuLcG3l
            U2ZDxQYC6YJDpwEiPd5JX3fbUAfmCB1Ibww4rIO1+3ofpuj/KGZ4IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-22T07:21:59Z"
    mac: ENC[AES256_GCM,data:VVAHPUgPJAIW6AoDcQHGkLZpO85j1CFlFukIQhHfai1jsOmTqvKNPtra6mCpiqtSEguHtJTWaCUUJEJMKx7eKvzRSgsgVXHHMnbJJ+Tbc00omMYz6q48WF42w2ggfL717S8X0P03lyrCG9Rpf2w7RSoBKvS/npGUusw9kf8qUwM=,iv:HeLHJLfSCtty+iL3eCzY/D3yhdeGt9NIrltpFpUqmH8=,tag:9ehVuXx4Nmt0XXNcwRvALw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
