kind: ENC[AES256_GCM,data:nUJgmyJb,iv:Cb8CbaA7oo3OMZ3Ho0O6fMcuGKbOi9xVWYnjf2CRsUA=,tag:YhhltqA+T2Rs9d6Rc02nDg==,type:str]
ansible_user: ENC[AES256_GCM,data:jMN6Q53k,iv:w+cyLhXR6tmR45D0tOwOTEZdFEHq29sgX9MG6sh6H9A=,tag:TjFtNa3cIjQJzrN15WGslw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+35CAtNxojoldHRnvNdPZBJ1xsc=,iv:Ra4wdCsxYgguhcHYBmstoHR5pN5WRcoV6jXajjFQ42Y=,tag:wy8MGuWlI/Kvc7tUBNBIcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR0VnV2FCdjdCbXFtZ3E2
            SHhBbXNiOWROeFJyQ0hhY01vOUh6aGx5aERVClJGUmxtL0NtLzVxQUFwTTBXc1g3
            a3BRTXMzcml1ZWdCRm5NSHY3MS9CdlkKLS0tIEhILzVHVGlNYnlNZlY3T01Pbml2
            R1F1dnBjdnNvb0cya1dDTk1rOENPbXMKkqRP4QP1fw3TJqn5e90DNgiT87kUjR7x
            C2ojjoo7I7r8pCHKjJ+xYwNg3twTivtkEFwYVa9IqgYET1i4OV18WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T04:03:07Z"
    mac: ENC[AES256_GCM,data:lqRcC+H2V3nvPd7+cw4DUdtkjlsPIlamt4KjVZcFcvXGaqK3cO35LEmdPGuLvBWZLchre9tJ0ipKxSXfWl7UjMRHx4Rogx2JAtGzGjFJ4NhGDvegBfk58G7VDOnIkhaosZ3eOfF9l+g9PaMXJVjn7ks/RNmi7N1irohzpUg2bBE=,iv:cAQSsDywcEkL4RYImf5vVYHRGVLjYn4V7aJk/oMLB/E=,tag:z+fMxEfdWFOT8JkDjuV28A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
