kind: ENC[AES256_GCM,data:gcW12LrP,iv:5ILmPoGbLyGjWg2pYZzW4zemJsN7wJJ6Nfpf1DOZHLE=,tag:a7xzgijPY8QccaefcShkKg==,type:str]
ansible_user: ENC[AES256_GCM,data:WSJe5f3W,iv:qBgng6mwmbFEfUHxMRkSXaBgz599Uh5ek3w2iKzWDOE=,tag:pM8RNMEThv3ySB7mEf6SKw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5r9WH8pht/z73MhzzYIRE0yw6VQ=,iv:kW9FUCtgmOYOhvyU2k9F2lUeIXDJH+cNlDK0d6qzjLM=,tag:Bjj6wvlZFh76kizeN8TOrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb2RNZEtURitWaitWTEtE
            d2FtRnV6aVZnV0dmVDZvSjRQOExrTzYwU2kwCmxKbjBaODdwbEhEUmN2cGQ2VWV6
            eS9EQnV1TDBQTmdRTUJVcFJyZlJaeEUKLS0tIDdVMlVXdjQyRXRUS2RyL3JveS9Z
            aXFDdnBCbUlQT0JxZXJrMDFpZml4N00KQcbMyFXrebFuVCFjNMynFPnwTGuAQ/1D
            5tZJqoMBYJ/m9MmysuWXm79zv0u+sC6J7AWE8JN/5f0RBpu3Pm4y3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T04:03:07Z"
    mac: ENC[AES256_GCM,data:MhwIhAWQSz6PP2LInyZZjnCf9VlCwX5Cyc2SFZ5QGN4KSVW0GO+ZRBA0d43S9arMmmfv2A6bKn9J8D04OBHWEvgbPsdCSY3JEaO92MjIpmKMzMJRR8MZ6CeGQA9GqVy0lj3SEM7cq1NRfmZm4KYtbRnrwutqtJDVe8eFe6SuNJo=,iv:Z3cPUZHzZaSmESAu9adONackH/cXZBQ3k0giA6mh4VE=,tag:O8yfkmBiN1CC0VGagQ7zWg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
