kind: ENC[AES256_GCM,data:VzDOTeg9,iv:DhqExg+YLF/nfPqOLoDjRrR9yNCyGLHv+ASJkUT57pg=,tag:qEpRbrMst51PSoQyBiL8lQ==,type:str]
ansible_user: ENC[AES256_GCM,data:e2UnHs0+,iv:X26ndWvL+Sg/Q6nY8X8Mu0jUwy4C+QFswRxKa9a8flo=,tag:oc+7NmDpMsVU4W22h5OxOg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:B4Wc4ICmQjba9r7A8G6Oodg9KNo=,iv:oWjSYl92KVHHhXW6Rmk5Hbet6ao5Dke0Sn/6JbzGUl4=,tag:uxkv566UeWm17sbzQztvEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTDYzcnBFbmFYU2ROUisy
            OUo4ZHJuMmo2SUt0eHp2WWUvR1Jwb0NiTG1RCjd4anBtOHNndmdDQWNBYWk0RnRF
            S3pGK1VwakJsWnJaVFBaVnBTWWFtOFEKLS0tIGlNMXprVjUycFZ3blNOK0JZQVps
            elU5bmRqRklKOVluSXUwZEIyN0Rkd0EK6RzisMZo11ZniW6Ha2RzRb/JawdOIIIi
            ZcQRit3j+B0W2Jfq1B8eyIMjDyhdBvjM/8MW/a6GabjeQApcws0wwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T04:39:00Z"
    mac: ENC[AES256_GCM,data:THw2dDHKhN2gQGq/bu1xb+8ZfzNXYicTBe63ZGcOuTaAnD8SShYZ0kdU5pt/WKUsiYsxBEujQvBCAn4sHV7v5d1PBTQSO1313LAjqyBKLASkr4RLX1yjrR7SzyZAvaVvpwqq/F7L+QvZpggZos+wSgpdV2EuxLsJ0MBB0tGwsUw=,iv:QJID0tuOdgV75GWig6B4v4JSgF1lgBVVlaadVZiWAis=,tag:L+OJ0pYQTAil58un8Zoa+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
