kind: ENC[AES256_GCM,data:y8ON8a2K,iv:ivhkOnSS0HtWwmvZXtayaiSqOWdVjndyNykVbfeCINg=,tag:Ggy35dmnilj2vay6cPa4cA==,type:str]
ansible_user: ENC[AES256_GCM,data:xwo/svVE,iv:c4ALF8QhfPyR4QcL/UiuJ7wljm6jCfwx4OG6beQab3Q=,tag:IDYZgHKs0bIc+XKCVNr0xQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qd9YrfQ2ugEFVBLyD5eX/+LFfQg=,iv:riROYoWC6LVyHXUTOv6GCZk94rtsD9n/LCr6x2drvQo=,tag:VSaf5L43VsXecPQVY8G4MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VmhyUHIvaWluYzdMK3gw
            K2pYcE9hQnU4dUdJMFZUSmIvb2RnZVNyeTBrCm5WV1hUS3VialNXTmNUUndPK0Ni
            ZnNuMFBSSEwwek1UeVl6aG1HMlBBd1UKLS0tIEpQMm9idEx2NkI0djBRcXFyUFpJ
            L1lnek5RQU9EWTg2dzhubk9uQ2JxcVkK2NyEyyQyLf3U+3Z44y7R6K6iCTdBuGQv
            qf2XAVf6j5bxZMmt3ZY/pKPjuUhGiuknbcNULhkeRZ8PHsQkBgVmrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T04:03:07Z"
    mac: ENC[AES256_GCM,data:YAhlmFbz5HLQIVLhlFkMUkL7iPgJ9+IVaUrNZbELu6bUM5c4LO1YJJRcM8mpD4Iy4FVJTILatFaNHwocHPL6fF3S1dBXSqVUkFX/NLf8aRhaHyJsrBXYYtD0Co/jwSEAId6Sj4IRgwED17rY8ON+k9v4oWEi1Pv/En9xVnIlj80=,iv:d12TStRzetl7BKANwWfarj2glvq5aqTg3u5ofyS63iA=,tag:P/tdjaMDOlDzSDVWATz1aw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
