apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:YW7pnKQ=,iv:Djx8svwqZ71cW+Yi+JujZg4ynjjHW0gEIi5PSFJAbWY=,tag:HBRl3GVm6WfmdQ4y4tjvMg==,type:str]
    admin-password: ENC[AES256_GCM,data:RYz3Mo2t8m7rzMhRKBBqtxCAPVRWH8PX,iv:ItePMSPwtlGQgqxzvFFw6ND/ljCeNqGp6ruVR1j0sMY=,tag:BFX3nP4eDrHFa9ryAkIwMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTC9ueTFXdndKZDlDd01r
            alFsclppd2ZuRHcweUx6citkanNXa0MzUERzCnpkRWdWT0VWNVpRbzhVL1huRkp1
            cjVxYWcwN3kwRWFiR2RHZDlabUQyajAKLS0tIGpMWkFzaEtoWVZrNmhPd3lueUVI
            NHZmVkZaclpxQWxxUVRJdlVrNVhBRVUKJbwOXdAQtHfbDMDVJaWA81dpN+Em/MYD
            DmFvhlloADpF6E9BzLRvrjAwj4DDlJgUo9S3mf3trdlBPVCPPo4GgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T10:54:07Z"
    mac: ENC[AES256_GCM,data:x2/BKbzWEDlSw/ltarRg1nKOK94gLcuHBS2P8jqrLmmi+1OUpeVuNf2LJ4dbIrPe8VY+Gcq5oJ1wGwxn7EZjY4efELvQGvfQ6RC3f5NeZDrPoDEaqMIJJ2Qj2PPOq07KHuzboWEED2fxxnvObS7yNXTFTEw+lSrtTL9LnW6LZ8Y=,iv:v1kS5Kesoj1jEotlFDAqlED9jb/GtJVkn62zYUUpwc0=,tag:kyQIKUASz25phN4PGwTS7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
