---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "minio-${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "minio-${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: zerossl-production
    kind: ClusterIssuer
  commonName: "s3.truenas.${SECRET_DOMAIN_LOCAL}"
  dnsNames:
    - "s3.truenas.${SECRET_DOMAIN_LOCAL}"
    - "*.s3.truenas.${SECRET_DOMAIN_LOCAL}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "minio-ui-${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "minio-ui-${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: zerossl-production
    kind: ClusterIssuer
  commonName: "minio.truenas.${SECRET_DOMAIN_LOCAL}"
  dnsNames:
    - "minio.truenas.${SECRET_DOMAIN_LOCAL}"
