---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pihole-${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "pihole-${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "pihole.${SECRET_DOMAIN_LOCAL}"
  dnsNames:
    - "pihole.${SECRET_DOMAIN_LOCAL}"
