---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "proxmox-${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "proxmox-${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: zerossl-production
    kind: ClusterIssuer
  commonName: "proxmox.${SECRET_DOMAIN_LOCAL}"
  dnsNames:
    - "proxmox.${SECRET_DOMAIN_LOCAL}"
    - "calvin.proxmox.${SECRET_DOMAIN_LOCAL}"
    - "hobbes.proxmox.${SECRET_DOMAIN_LOCAL}"
    - "susie.proxmox.${SECRET_DOMAIN_LOCAL}"
