apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AfEHbzKvKFPIkJz+EFyAIy8Z/nFf9qrQ,iv:7JCR7N/JDgg8j0EZn9hU9u6ub6BK8rF7AUCz5lqbjXs=,tag:hBOuxVfZJJ/+mZ5hOYQIfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOREdMb2lxbGNibFNFZzhn
            N25TOEdZeG9XNWVxTC9Kd1ZhV2hrNy9aV25JCnEyQTRlR0o1Y3gxYXJUSTgwbGcz
            ZDdCMVlzUTJkQzQzNFl5U01CMHRsUUEKLS0tIEJUS21POUJacHFnVDdBb2FlZzV0
            Wmtubk0zdFdqa05GTTlWVUpMWnlEUTgK15AQ8f0aG4Y/7xXpX72Em10cJ82wIPDV
            zT/dMYk4HZcTeOAOXHs3Yi7diu0DD7CnOtyNEl6fGIO0a8WWbOaiag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T06:37:21Z"
    mac: ENC[AES256_GCM,data:EH5BuhlyKq3K5Kc/eUt9i5qoOD6bh+GyhxKlyuhK8HCVzvcViAPuIodQJXbrbtqb9LvdGgsuU/DT20f4wxa7c+RC2Nx54TqYPagmaCvmgtafFeWbNtxsU/6IdPJ4//TayVqtV9kWuIMVoWBLXSLw11MNuay8HIy3giskBMvE3Zw=,iv:sgvccGzZ1VMo9HN7JYiauO0gjdLhWWamYg6RxAbe92U=,tag:/qkREaNI+Juji4Hvaj1otw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
