---
# A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
# Update the values below as needed for your instance. You will be required to update the
# API Key and URL for each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

sonarr:
  standard:
    base_url: http://sonarr.downloads.svc.cluster.local:8080
    api_key: !env_var SONARR__API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: series

radarr:
  standard:
    base_url: http://radarr.downloads.svc.cluster.local:8080
    api_key: !env_var RADARR__API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: movie
