---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.32.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          s3ForcePathStyle: true
          s3Url: https://s3.truenas.${SECRET_DOMAIN_LOCAL}
      resticTimeout: 6h

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: velero-truenas-secret

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true
    snapshotsEnabled: false
    upgradeCRDs: true

    cleanUpCRDs: false

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
