---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-qbittorrent
  namespace: flux-system
spec:
  path: ./kubernetes/apps/downloads/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-pod-gateway
    - name: cluster-apps-longhorn
