---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  name: backup-daily
  cron: "0 2 * * *"
  task: "backup"
  retain: 14
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-6h
  namespace: longhorn-system
spec:
  name: snapshot-6h
  cron: "0 */6 * * *"
  task: "snapshot"
  retain: 8
  concurrency: 2
