apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    cloudflare_api_key: ENC[AES256_GCM,data:QJbchvs4S8k11ZS7zJ/QrCTaGTCnRmOnMBClizNTTwFE5YdEbw==,iv:+WN/KhO+mVj4mD/JKsR3mFnrlkxyRZW/krQE7CvDu/A=,tag:PNipw0rl5Saw0ng6cmWi3w==,type:str]
    zerossl_eab_key: ENC[AES256_GCM,data:FQmrGF2qyR8Uh9qaECI+8XQ9UMS+JkpFhi/Jx8CoJ6dt+74mwFcIR40KFutFIlEenuP4kj71e9CpARMqprbYtlreyE4/gMZHRlw8eFL2NiPfA40B4aI=,iv:GVHQZSe8e+R2ajerw5gzfHxVmbiL4x541e6zqwFRHYU=,tag:UmXGYy/Cp7IjDQPrFZLpmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTENKZHFPTVZpcDdVMnR0
            YytGSFljVDZTNVUzYU9XWmFVa1lSdVlYVURjClpNNTI5WXpvRGJTMzcyM0grTkRq
            Vndqa1NGc1llRForb3FodmFrQXUzTHcKLS0tIHBlWHVIUnZaNlFjcm9ndjNoSEph
            eENNcS9kQlM5UW01bHFPbkZRd3J6OWMK2yxin6f4NdjQQAb73sSkdILgTC0cwdpS
            EGRKpF9N33lTcoK1mTGHwUwfiK91knD/wc/hRqeiOBfd+CD8qlYd3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-22T09:47:23Z"
    mac: ENC[AES256_GCM,data:iRgIkY94Ch85rITDl9YmFw9PfYogjNlFs9SbsSzYtlFBqkZoicmgqVyKIxq6Eabb3CeC/C/pcbzPuAVYH0h3TCA3D72xw1L5UBjj7Ga+ifRgO+D9jaEPwjYhi9+8V6ea+ivw1UZYkqDgezSPOwApVQaWpwn11l3wrOTPOOxXkpA=,iv:kzX0M9OzRRpJ4jZHPs6Zd9QhV19NDbwUI+/ONMwOi0g=,tag:9m9ytC4csmJuKQzdaemcbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
