apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Pkidgm5U3kXCo0W5r2erVf46DcvRSJ1CWqlxhkLsR34kyiU=,iv:JWdA8EqTW2BhXXQtdXoKQBJvLpUj28ku14qG//dON9g=,tag:sWTJ4ZWGbbjx3IOZI1Vyvg==,type:str]
    api-key: ENC[AES256_GCM,data:UiK6W/5Ay2UqthLc2ENFYWSnh4+aLeiwVBHbv8aJBf1lXwMKYg==,iv:nWtz6Og/cDZuEGe1fv/AZ7bRxwK/O/D6DdzidAPWn7w=,tag:1YeYXHGcJXw/nVkXR5i5VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z3BiUE1vU1dVcjRFeWU2
            TkZzK21jSEljT1ByNmNyV3VrNlBBbFhWYVhJCkF4aVdkeHkwRE5zcnZBaVVCVGdZ
            aW5PZHpodlNBZlNNZ2I2Z0hoMUNBMjgKLS0tIFdIcXB2b2dqc2VxaFR3azN1QWZy
            S2dETU5wNkY3NThmRHFmSzdEZCsxYTQKDELPtQFfy9q0KnVLyrmS8AAtJjhp2n9r
            C9fW8CMnC8IocnSl0k59PfyOFEsJWVGSGg3jLp3Xt0eYzVVQsyySHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T09:19:21Z"
    mac: ENC[AES256_GCM,data:BUlB5+0SvcSEKIqtiFisgHrZGZVY4nek6SCncy53iQT0ctUC75s6kIi+BzsJQfb+mLmWb4GMOzGYdG9X6f8R97Rtmxj/SjR41YO5m53UJmsJIXK5RxfKERJX49ESb1XVorrihI/9fkrVoHLL+mx8AR3OCVThBrngY7xkxfZ1Nbs=,iv:pWMYCftDEpFXdZo47t4WzIqK4dBNa/pT4ElZMm179OQ=,tag:PbpmajxC3fGwtpXv/hRewg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
