---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-data-qbit
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_IP_ADDRESS}"
    path: /mnt/nasty/AppData/qbit
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-media-all
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_IP_ADDRESS}"
    path: /mnt/nasty/Media
