---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/bjw-s/pod-gateway
      tag: dev@sha256:8d6c9bfa73bef0c5cc3fb82de17e9f3092d360613a0a5e11355a968e91a291f4

    DNS: 172.16.1.1

    service:
      vpn:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster

    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.34.3@sha256:3b4d498939ef1f9ceac9049a73598acfcda25a9e58010fcd991afed32cd16eac
        env:
          VPN_SERVICE_PROVIDER: "custom"
          VPN_TYPE: "wireguard"
        envFrom:
          - secretRef:
              name: pod-gateway-secret

        resources:
          requests:
            cpu: 5m
            memory: 64M
          limits:
            memory: 64M
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE

      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 10M

    podAnnotations:
      configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway
      secret.reloader.stakater.com/reload: downloads-gateway-vpnconfig

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_INTERFACE_MTU: "1420"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "2049"
      VXLAN_IP_NETWORK: 172.16.0

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
