# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: downloads
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:WQXJKJGlj7I7n+qV0iBv+Nh+LdHetVcp,iv:9Jlukpj1M4MyERnAnzO3tCZOmLXGjeRjmfy5phcKbok=,tag:+SjMgX5hrIl8R2LwdGEoGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVzBiR2xpbC9taUg2UUVj
            d000ZHVTbk95bEJrb0VZc2ZlSjlqc1FGcFhFCk5lTlZJMWpTRURWbzVJWGhETjNY
            ajN5bndHdk13a2pyYjc1Y1RDUXhSYUEKLS0tIEI3Z3Q0T3pCTUNVMEJwNlFWQmha
            MVdzVGZ0em5SRi9HeXV5M3o5MjZNaHMKXGTIfk1YX0+cO2i48+phmCkvpDA9fpz1
            VZcxgclY+AAXJO7CNn44bCVJ2ry40cCV86alpiDbjnalMyXVJFoc+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T09:43:41Z"
    mac: ENC[AES256_GCM,data:N0PV4WW/n1WqtRtLDD6hCRpu8aj9tw4umjkfU5TAHAtJb+9w0NW6afdBG1zIdpyn3gPrSagvzebhqIJ2FEuZVcduWPv0YVXzsrzf8Kqc+5VXwbXT9rOYaT5xM3+wPY8PEiPaKI5zuCPXZwiG2pKOY+/DryISHn0lqrfvB3Gu9Cg=,iv:BL8eEyDdQn1CTyGdhy2X538J8Wr4TUw47ShlKqKBP6E=,tag:IhkFaHH9llKmjejjHTDXcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
