---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  METALLB_LB_RANGE: "192.168.10.0-192.168.10.10"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.0"
  METALLB_INGRESS_ADDR: "192.168.10.1"
  KUBE_VIP_ADDR: "192.168.10.100"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
