apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kKtnXWlegk1X,iv:5gjWYkY2nMRLoUDb4Q1nHYhe7u2s+uypeSACnrZu1Mw=,tag:HT0ER/LclCmj+VA++EIrUQ==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:QRnIWQG5tw+6jFrZneec,iv:HjAJBV89D+HvUO6p98ljU802tuhDg16GwEq+mYiqS+E=,tag:jQk5iF/jb/+JDAgzGoPedQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GeQyIMAWDXdWHDytOYG/LoyfQwSSJf61ePqt/VOJ5OQSnkQ=,iv:IsMDwQnqb5kdz8NH8tvxAtyJxOdrRK9R8wBhWRNPwkQ=,tag:2UTh3gn50owHE1dx0/z6DQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T2Fgt4nwwBv291bt9LzDbMD3DfALUEiuZiUH5o1uzrs9fs8R,iv:qT4kqIY1fcqo5OqK7hci56VAyESXsHwBqwVIHMQzw8s=,tag:c1QQGJDM6UF6KMhIH59iEw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:pflyMH0GdOs0z4Zgb6xIL9w96cBMjsxbBTlPDdX5ZD0qRcP1ufZKBQhOBjusL0qKfA6Y9auvN1AX/v8IqINDNfGY,iv:7F3cX2WOWG2WDTsvY31HKDEq1bAESZH+nr9A8PyVUho=,tag:pvLuptb4v3NFRREkP1S8Qg==,type:str]
    ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:xxWNSM4We6askDkgMSigkCSaYUe++WGtvRa8E6U8bLucKoRF/AmrFjQEotZxpIZ4a9nPKG7Q6ESRyciRdVmNaqb4VQESgQUPeqDJtmlZGa9QbQ+vto0ziPJNz3OdMSZEiJeNxuz05Xn2IwkuabUFVe5joHNztN79oQ==,iv:QzdggJ8RNcXtsIUY5rd7t8YbzVI7aQP+ZmXiKHNK1I0=,tag:/0lzn+uEzR2+KtGAF8V8MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTVyYlIyV0Q1LzYwZTJr
            MWRLdHhyeHZXa2QzTTFLS1JyM0pXN2VoZ2dFCmFRTDhKTEg3MUthNGkrUXdnMUs1
            bG9LYmRwdGJKSW1GRC85SGkxZUJXSjgKLS0tIHM3dWZMQTVsY2hROUVkN0VJc01R
            eFJ4V2ErR3EvczhYMlIrbTVzanc3cjAKjCE73+NstnZc35Fdxkzy1ou5ha2qhONG
            g4LrYKCyjepWJyoXSl9UFdlkapBahjd6vzHTyOYh54GZfDT+ybO+9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-13T17:35:25Z"
    mac: ENC[AES256_GCM,data:IGuoRuI6VECQPas1TQyas5e6f1cbQPl6+9n0WZsYxXG6RAljIqnlttfWz+05tCMVnk8vdi2rnat+VzmGZKPa1hwxo0egDOJRounrL2KaK3Zqm6sA4sas0Iwg/0tpN12k+MLG8vwR7Qk701H3QG/AWwBmUbbKlomhYmIflYc+yXE=,iv:mZ7P36hvOkLWAFUrHndgf8fXzNFRctsIjFfSKvFKndo=,tag:3X2YZrW3v93ntecVkISdtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
