---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-media-movies
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_IP_ADDRESS}"
    path: /mnt/nasty/Media/Movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-media-tv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_IP_ADDRESS}"
    path: /mnt/nasty/Media/TV
