---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-media-movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-media-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-media-tv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-media-tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
