apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6LWpzV0=,iv:pCwXr0rI5lECNbJo+wfQeahjVy6F9wOU/2UCU0AxVjo=,tag:k6LuePSHRkSD3UOaq0cEXQ==,type:str]
    password: ENC[AES256_GCM,data:49Bm6Sl0hqIvT04310fnYWKcwAKZIwqwR2RNEZLvas3qM+hM5oPGt6fuW8Li7upxxqADycHAIkL/Yb5e,iv:EICPTVNCg1IPYyKaCBbTtmSS8rM4PSzgpZy329TVLhU=,tag:PNVeZc69f3gd2fEHew0CFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0JiMDBIZHgxK3RWTDdp
            YWVEM3FwbVhFdW1heGpXV1EycXFVSCtMdTN3CnRUMDU1a1RrYkU4TFRpdVdMRkJC
            UmhsVVptcEVlS1NrT001YkhnWmFqVEEKLS0tIFNqS3BjNURWWmtwZDErQ1gxSTVK
            YWlhQTQwdkJKdVIvMm9DQjZkNzdyWVkKAf8dOGb2S0NuaX2SLEkXzjIwmd1ID4Rd
            urJ6rusB9npx52f2g3ggDbtbiYbbGBJAgiH882+3PO6IS7gRI+l5gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T21:47:38Z"
    mac: ENC[AES256_GCM,data:EdAdjyn1QrRDYm31/EBC9he98Otpdw2a//GwYoJj0SdNizNFkb1eIeiFJ3AphsAo/xdAYhTquwYWEZtErp81+fOjwpU0B0GOid4p9lnsqO/s3fIgvsoj26cNkNroG2SS+J1gkIY5rkJX2xoIYTayPe9ezrWstnILBK2W2sXyAsQ=,iv:iNlY519gN2s7eFz9PC/KixDve/l/w2w495bL1Z7jP1I=,tag:8r/4XvXegXGLiExElkfzOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
