apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:99bueU74iUC24i1QVe0wzKyTvywaN2ympbnDMixcMANdNuy/Sn9+23w4/t0MPVjv9wJt8T3IdvK7NWFQ,iv:1rwGo9vKonnDTm/m6fiP4DdQi44JBsn5qz9U1JFeYYc=,tag:24VTObJCIfArELlpgPabgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkVCcFVIOUduMVYrUGtv
            alhjRHRiaEk3N0c5TmtQZnZEMnZ3Qm1Bb3lvCnhRVWhTaGtTeFZ5b2FhTUo0N3VZ
            Yi9UL2tsNnRUR01MSmZWbHJNK3ZlZkkKLS0tIHFnQ1FBandQY0V3OVdBQkhVVHdq
            OFlIN3dLbjZtYTBvdUhuUmp0OE8wRmcKd17NZC1g7Vb4asf32sXkdYR76awaFBOI
            9ob8omfew9Ehe7a5vv+3WUD2r0wtmkZvSv8/mu9udmxHDl6ejYlsbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T10:54:07Z"
    mac: ENC[AES256_GCM,data:HhwFi8XmdKcxZDuJVre9dw5MsaQcqleN2eRWF3DDsz2noN6Up0QlC14fxXPwVzRSu/b+nLhRFEoquBws5On16vdG3cjhhTI3JBOPtbvWe5y5HBxhQ84OBpY5Lyn0/phXvleWAToQEM9OjPkidQ5AYh2Vb5NC27aU9ZuI50dC9u0=,iv:jF5lhyBRxSrejAooRgf2Fa7/V3zNdBV9Vdi7XKWKzls=,tag:q3Zoyom//lQrdu/80oWuTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
