apiVersion: v1
kind: Secret
metadata:
    name: radarr-exporter
    namespace: monitoring
stringData:
    api-key: ENC[AES256_GCM,data:QOeIt/dfHGPWVJ5fSPcN3QChQtgHHrmq,iv:b8FsPGKPv7xXsze7dG5r1WmBqlkCFS1I54HLgZlHlck=,tag:a05nd6L9ESn2qTZVE0jW/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbWgwMzFYQ21MNVhvcTFR
            TUd0My9DSTBCZkhvSnQ5dExhaWxaM0VHdjFZCkduVnJna2ptcGc1THJ5M1NtSlUx
            MWVtc0RIY0dqMjk1N2duN2pZRzd6UE0KLS0tIDc3cEpHQlFqQ2p6Y2hhNGVmcXph
            OXNPZ1NCQSs5NWxWS0UyZk9rT25Yb2MKnfwsf9Uvx3VJzsp6qx4wuCmbI0QzMdEO
            QASXsBd6bmQh4uKllraV4alOYBlOjdUddiR+F4LwtjjMSJTxtE6A1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T03:41:46Z"
    mac: ENC[AES256_GCM,data:TRWnVv8DG6oE0S/+qNHGpEKTwYLRvuXT5cOqLUaHsOHqmhPt8UhvK/YWFvmHuGm+YGI2YYIDnfNPSHedv0IsLg5rEVkzAt3e/g7K0AAzNC7Kvc7YxhN9WjrxMtO/8MrjnurkxF0l06QL5YVyIWCIB6Rx9n4h8h8XRO3Jc/jijrE=,iv:KPbP2wkzhONMiU8STDDLcoGFtKLq/8xWlsrJYWukVdA=,tag:vDOjox/GFYgElrVa4hX6sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
