---
apiVersion: v1
kind: Service
metadata:
  name: &app susie-proxmox
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: susie-proxmox
  namespace: networking
subsets:
  - addresses:
      - ip: "${SUSIE_IP_ADDRESS}"
    ports:
      - port: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app susie-proxmox
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: susie.proxmox.${SECRET_DOMAIN_LOCAL}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 443
  tls:
    - secretName: "proxmox-${SECRET_DOMAIN/./-}-production-tls"
