# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: downloads
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:A26iLOTgjAdKpas3qX6r0+bvKK0qF5Ay,iv:7MJaljOwKd+0HColh829Qiqm+L30nfIR1A9OZ/zYI1Q=,tag:CnLeHRYNDNdikFGbNKnfMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK3BFeEltRmpsZHhkWFEv
            MXA5UFFqMHhPNk03VHFDY1RkQmptQzdkZVFRCldQSnRvMU9EVmo1bHVmSjFTTnhH
            TFgvVjZwR1RCUzdwdm9rOFNYaUlPQkEKLS0tIGF1OUx0eHdRQzlQeGFKVE1ENVJK
            d3hydnZWTWlucFM4TTJ3ckVqSExsQ0UKOph3GZNDVpyIB6QMUDJ3VDvD8gjNij25
            NYnXZIXkKfwc5QeABYq9lKh+H87zgrRhxcEMmE4ceNCWVREPr0zBgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T09:42:58Z"
    mac: ENC[AES256_GCM,data:15vLT4eNkNdXNNPqq7OUkbmo1J0ExZ2Wp8fEQwcsy9kIHmYoamqbwCAwYJUtylc8xNvrVZernZHGKOPOUqKPl+i5FVxb7uUXY/xcFcrnNL8nduyq1Jca89LG8w4sgFSS/T8W7W3UPYRliqh0shCk0XiUU9Kwu9AJqxi1lnDUr1Q=,iv:Ad+TqrEbc3ii/yEr3ZZYTJYtUufksAw+Gjf0C8Zs1Jw=,tag:wp9x7LK2lj9jUopFEJAuqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
