# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: downloads
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:xI819Ps8VkeMKHYWEBFxbZwKN1vZlj2i,iv:N1j1AI0eI5bWRYe5Dc9us98VmMoF0Jg9te1sAiZc9yw=,tag:6ruQWPXElJwfCx7aiTeLFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU2NWTWJqTzRMQjR3U0R3
            T0ZkVXc0MEVlbnl4R3lqU0g1VWNFSGt3ZFdrCm9lYUdFN3FaUU9YTzVweU5vNlYw
            RERLVlpIb3prN0w4S0c0Y3NocTBieFEKLS0tIFhVelhubzB4dGJjM2E0V21tOGhh
            bFBrakVRQ280Zi8wbE1vcktwQ1dKbUkK+PqiHuet0v1rauU4mQrrKxZbrRokwwXF
            APoTX+80CYlNrZnlQRUtdq3gI3xft4EGFKdEeCkzKMd5k9NUZIhNLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T11:00:12Z"
    mac: ENC[AES256_GCM,data:qPJgjnhoTtHwg2hZEg4reCOZY28e5xEXQzcrOinVdenrLBLCWdcnnAAE6YDLb91V22fh6ePvOjFYwWArdApWVsw5GPjwWFTwneHPUziVYnRAzwQmdpqViAnXxZeTLwyMXsFnhZb1oxPdjsIBaFuYTpirWqi1eJxxIJtwHkLMYMk=,iv:cX9TJ27qG2ZzmZTL+IldM01tHwmhPEcIb4d8iB7gOhU=,tag:NMbDbXoS0RHaUUPR94vIHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
