# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: downloads
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:ECgRoTIo404Z4842+sNu4eEEjpOILluxq7L6RXPSAs4=,iv:MqNPCG1/3drQIeZ3u8s9S8XkRE+A1zafOSk2qwiGOhY=,tag:gP6ERadbUcDFtMAZ3IU4Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bS8vc3hHdE43ZFYxMGNn
            STkzYzNPUWFWZEpoMW9OZXN1cEpOeFJMMTJFClhxNk51MXJWZXhtZXlZYmUzbCs1
            YlZIeFFEMnpvN2pRVEkrNVB3aC9BbDQKLS0tIEJWYlVlUnZwYys3aXA4VVcyMUx4
            SFhqbWU0SjdOL3NONlRMUkZNZ2lHNGsK+l25jOFwEhoOwgw4y9WO4fR6OsNG1Ssn
            vYe5bNsNxg5okiEtklPJ5v5TrkeTBKlfgOtbdC8GDglqgeKaTpBjWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T05:33:19Z"
    mac: ENC[AES256_GCM,data:yrZpEi9KvRL4yGuuPN5dSdVetpLXIJ2qp0vr9MR6AXHUgTfXsO2OlHBn8wHyeWRsX84qV26L2JzP5z0LoH8GcBq1wqAL18LJcCMttlpbuwpDL7AnbGaY1YnhC9WdhOX1QHm1bnpbLoo88AoXhwn25QG9/cACBf2R+qsWLa2iTMA=,iv:z4t6gfMZ8Wz4YCqI0ZWQn+t7oW+dpLLxt+/4MkNZRpQ=,tag:ktmspFEkAXZkunve570iRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
