---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  interval: 30m
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
      namespace: flux-system
  chart:
    spec:
      chart: grafana
      version: 6.57.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    grafana:
      enabled: false
      sidecar:
        datasources:
          enabled: true
          maxLines: 1000
    promtail:
      enabled: true
    loki:
      enabled: true
      isDefault: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
