apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CFgpkhoj1OGahfxfZY7y,iv:6vNDZrESlO82LfjHWA3rnuE8NqUmQs3qmryDjqd8bhk=,tag:PTJGFh785OQt8p4t1h/bmg==,type:str]
    SECRET_DOMAIN_UNQUALIFIED: ENC[AES256_GCM,data:WfYOrDQ1fm5q,iv:sDVMnLyb34/B+5roT3+NJlV/rhBAbAu2Kw9wVzL658U=,tag:3QPOrz85GI7MsE/40buvvw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zuHzPuZz7D8u50jBNrxPmknkcCmT16Dg1yXc7l5T/Egm51g=,iv:Pjztd8DGrJihRY3ZCfX3JtcFg9Y8zmCQDCA0aPEMkzY=,tag:TxtdRZzfE0NOLbGF+OuKMw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:DB9TwIHklBaR2ZZu3xcsbDRlmdTUi9ZoLDuTJVbWFEuis8dq,iv:QoOSZb47ts+6L60SInVKVne76OUQMZSQo+UE5iUVo7k=,tag:VfWg7pSZpHs81/29S+JNFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOVExdWVUMWxOYzlJcysr
            eGJzNGs4bk9qMXIvbEZnYXhVaENhR2d3aGdrCmlObkh3Yzc2TnJXTUF2TldiU0Vy
            MXRyaTNrYkQ1YkVKNFpZV3RnUEJvZkUKLS0tIDJoZzE2ejU2VVErd3Bscm5vV0Ew
            UXJFNnB3K0VNUmhDRWl0WTNLeG5NcEUKLRnduFJFbPOo2mjmyP31vAaZlOlpcPzG
            RCjQsjKHBXcoS04Ok5icrYFKVBprQAxSP4Aq34JfsaOeOUiuiw3+Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T05:58:12Z"
    mac: ENC[AES256_GCM,data:4oERkuoLafHfJ6f5BcAjYLZw5qeEUGKDoC+vTz1Pyf6wU5lthhCKKh1bJ4BrvEgK95FxIXDtTeHYmT7V9nZvVFMCVNBf2vaFenxyx8lX0r3wP9FMRqemoZo+jdhR46XNn/sGZRh9xA+HALn3xbPSFKH7y8JbWraKF2Smb9hnnf4=,iv:D3LLuwcEOaNmD5Nujs3UcHjXNW9E/3DfASXvD4TgJI4=,tag:p3Q5qJQYacQck5BD4uyUOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
