apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xa/7uv+PUVJU,iv:rXtDhC+TFuAxn4xUsrFe11HjYrMgdLYdQS7RliJo+nc=,tag:2Svn8n/aSIav1tOmjQWNEg==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:UoPCEqbsyMO4K6T1DdtA,iv:/JKeTyZi5HzUJ9yKgSTWLLf4hUPfmQP9LMm6z9u7QqA=,tag:AWwVsxcmqvmlRHsYDoYsSw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fi7q1XUYbJykyCEmspHrtQn07vB1TBG2H4A51Ky0XUJ3yIs=,iv:he58P6qdr74AiY3yMepf65KgBea6KUHb25Ki5SfebtM=,tag:i/a3IIGjRj8WMWTlD5aFOg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WTDvzoAoPF+YnDseVj+4F5wIkN5/EhM7A2Af/U4k94ONdSB1,iv:E7e+e4JTBFSpcPbpmN68AfDBS6CWk/d454j+gdaxwqY=,tag:xqyk1y2eAKtcEjIdGCsyxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQWVKeDJpeGFnWnF1aktl
            akMwUHBLdHlrSTFOYTBJVHl1dUZxeHdqUlRvCmtueFRnQnJad0xkaEc3OHhQTVVq
            bDZBUW02RnZLMmpVUjc0T05FY2pxU2cKLS0tIHNEaDR6SzYxY1ZTQS9CVlpLckZv
            OG1iZFdkbG1XdktZNmZaRk9zSkI4VFkK0oUOC/kIDhKUfpFZXMnzheQAVJKCPsfh
            OuCrZsB5qmGNVcOKspatsgO7SyEIHUu2QMKMq+ee19nNolbK/jWOYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T07:18:43Z"
    mac: ENC[AES256_GCM,data:/w9pCujHq0cRkmZjGWvg+fle5/QRJqjVuDS/z+dG5xM6v3jVF+c0AGAc37tiUL5fugmy+42izCUN3AHuFqp+7oCdXCwDxiZAiWQxj12wtK4T9Hqn8k9kHOV6rl0yE1QF7SBfqsgtSkVMOWj/+KnIFfg0TdxE4u7zJCn/RbkHKQU=,iv:I3eqNHeoos1F/AFMG2IRCvtIE2d01yeBq+1Bu9K3OT0=,tag:TSDVQ873rG1iF6+KEMevkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
