apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XHzVl46lZiGQGQU1GbeY,iv:9SQQfubTYk0l5xl3Gh9PLMWmQu6q7t8DbomtLnrBXIE=,tag:vCAeyN8HxU2LnpBGFySMfg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:J6gZfXhJec8JA320XCBhfJ+6cCk3fI2kBVsWdbZVqoZxHvA=,iv:HB83164ASdtA6F7qHe0okQ0AkBQf/CcHEZOSt/et8EY=,tag:RLUC9bbJ3iwVrDI/LNEgLQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:7Q0SB+GtcWjIza87mXRn6qpDQp6DB7hjOzRxwxWXAlGhWFlG,iv:zAnIYlRAzMIjFasp+56usSauMeMiUYSahb7jxA95rSw=,tag:97XqFK38EPzzI0AIp6PHag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVpndzU2QTFGV0UrcVdH
            UzB3TTRRU3FiU1NjQjM4WnFPbHJWMVpJK3hNCndMUTY2eDVoWHcrOTNrQmNxQzFx
            NkFTRk12dzBDZzZ6d1IxRVdTVXhKRkUKLS0tIFJjQ01rdHd2alFmVVQ4OEIvdDJB
            ZGVyRm0zbXRmZzBsSkVRb29wcWdmMmsKdbhPujf95R2Y/mBAyJoj4V0e8/DGqSZY
            ELcQMMG/gUTv1IV5MyII5/dF1ydrP05zctvl5Q8yAc1K09db5pdwpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T21:47:37Z"
    mac: ENC[AES256_GCM,data:UhY+xzLfUHJkuhmrXu3q8sBFTIK+5kF8xoOfpjtOSJZ3dPdyBfzq8HfxlIE2NvtkEJ6q/EEFvv8v2dG7DjaH51v4VB0rPZdv1V+nUoJP0K72XD9hRlNBH486LnOvIsWVGa6/3/Fpyc/BaCGstdhk2zodxTsD+QEYhjwyRt0ZVSE=,iv:NZFi1UprYVOnGfH051QL0/ppMpTkcdMDr/f2Rl/J88c=,tag:A+ezku6xn7W+Mmjp2HCWtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
