---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.15.0"
  METALLB_LB_RANGE: "192.168.10.0-192.168.10.10"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.0"
  METALLB_INGRESS_ADDR: "192.168.10.11"
