---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sonarr-monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/arrs/sonarr"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-sonarr
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-radarr-monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/arrs/radarr"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-radarr
