---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  name: backup-daily
  cron: "0 2 * * *"
  task: "backup"
  retain: 14
  concurrency: 1
