---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_DOMAIN_LOCAL: "${BOOTSTRAP_CLOUDFLARE_DOMAIN_LOCAL}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_CLOUDFLARE_TUNNEL_ID: "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}"
  TRUENAS_IP_ADDRESS: "${BOOTSTRAP_TRUENAS_IP_ADDRESS}"
  PIHOLE_IP_ADDRESS: "${BOOTSTRAP_PIHOLE_IP_ADDRESS}"
  CALVIN_IP_ADDRESS: "${BOOTSTRAP_CALVIN_IP_ADDRESS}"
  HOBBES_IP_ADDRESS: "${BOOTSTRAP_HOBBES_IP_ADDRESS}"
  SUSIE_IP_ADDRESS: "${BOOTSTRAP_SUSIE_IP_ADDRESS}"
  TRUENAS_API_KEY: "${BOOTSTRAP_TRUENAS_API_KEY}"
  ALERT_MANAGER_DISCORD_WEBHOOK: "${BOOTSTRAP_ALERT_MANAGER_DISCORD_WEBHOOK}"
